ALTER DATABASE `broccoli_students` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

alter table BOOK_PAGE_TEXT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE BOOK_PAGE_TEXT MODIFY COLUMN TEXT VARCHAR(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null;

alter table QUIZ_QUESTION_TEXT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE QUIZ_QUESTION_TEXT MODIFY COLUMN TEXT VARCHAR(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null;

alter table QUIZ_RESPONSE_TEXT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE QUIZ_RESPONSE_TEXT MODIFY COLUMN TEXT VARCHAR(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci not null;